function fig = helperPlotTrackPositionErrorPerFrame( ...
    trackPositionErrorPerFrame, ...
    trackDistanceTolerance, ...
    scenarioName, ...
    topology, ...
    config)
%HELPERPLOTTRACKPOSITIONERRORPERFRAME Plot tracking error per frame.

    numSensingFrames = size(trackPositionErrorPerFrame, 1);
    numTargets = size(trackPositionErrorPerFrame, 2);
    frames = 1:numSensingFrames;

    fig = figure( ...
        'Color', 'w', ...
        'Name', 'Track Position Error', ...
        'NumberTitle', 'off', ...
        'Units', 'centimeters', ...
        'Position', [4 4 15 9]);

    ax = axes(fig);

    hold(ax, 'on');
    grid(ax, 'on');
    box(ax, 'on');

    lineStyles = {'-o', '-s', '-^', '-d'};

    for targetIndex = 1:numTargets

        plot( ...
            ax, ...
            frames, ...
            trackPositionErrorPerFrame(:, targetIndex), ...
            lineStyles{min(targetIndex, numel(lineStyles))}, ...
            'LineWidth', 1.6, ...
            'MarkerSize', 5.5, ...
            'MarkerFaceColor', 'w', ...
            'DisplayName', sprintf('Target %d', targetIndex));
    end

    yline( ...
        ax, ...
        trackDistanceTolerance, ...
        '--', ...
        'LineWidth', 1.4, ...
        'DisplayName', 'Tracking tolerance');

    xlabel(ax, 'Sensing frame');
    ylabel(ax, 'Track position error [m]');

    scenarioLabel = getScenarioDisplayName(scenarioName);
    topologyLabel = getTopologyDisplayName(topology);

    title( ...
        ax, ...
        sprintf( ...
            '%s %s tracking error per frame', ...
            scenarioLabel, ...
            topologyLabel), ...
        'Interpreter', 'none');

    xlim(ax, [1 numSensingFrames]);
    xticks(ax, frames);

    maxError = max( ...
        trackPositionErrorPerFrame, ...
        [], ...
        'all', ...
        'omitnan');

    if isempty(maxError) || isnan(maxError)
        maxError = trackDistanceTolerance;
    end

    yUpper = max(trackDistanceTolerance, maxError);

    if yUpper <= 10
        yStep = 1;
    elseif yUpper <= 25
        yStep = 5;
    else
        yStep = 10;
    end

    yUpper = yStep * ceil( ...
        (yUpper + 0.08 * yUpper) / yStep);

    ylim(ax, [0 yUpper]);
    yticks(ax, 0:yStep:yUpper);

    legend( ...
        ax, ...
        'Location', 'northeast', ...
        'Box', 'on');

    %% Optional export

    if config.exportFigures

        if ~isfolder(config.outputDirectory)
            mkdir(config.outputDirectory);
        end

        outputName = sprintf( ...
            '%s_%s_track_position_error', ...
            lower(char(scenarioName)), ...
            lower(char(topology)));

        pdfPath = fullfile( ...
            config.outputDirectory, ...
            outputName + ".pdf");

        epsPath = fullfile( ...
            config.outputDirectory, ...
            outputName + ".eps");

        exportgraphics( ...
            fig, ...
            pdfPath, ...
            'ContentType', 'vector', ...
            'BackgroundColor', 'white');

        exportgraphics( ...
            fig, ...
            epsPath, ...
            'ContentType', 'vector', ...
            'BackgroundColor', 'white');
    end
end

function label = getScenarioDisplayName(scenarioName)

    switch char(scenarioName)

        case 'baseline'
            label = 'Baseline';

        case 'openArea'
            label = 'Open-area';

        case 'piotrkowskaStreetCanyon'
            label = 'Piotrkowska street-canyon';

        otherwise
            label = char(scenarioName);
    end
end

function label = getTopologyDisplayName(topology)

    switch lower(char(topology))

        case 'monostatic'
            label = 'monostatic';

        case 'bistatic'
            label = 'bistatic';

        otherwise
            label = char(topology);
    end
end