function [scattererPositions, reflectionCoefficients] = helperGenerateOSMBuildingScatterersFromROI(osmLocal, scenarioROI, scattererSpacing)
% helperGenerateOSMBuildingScatterersFromROI
% Generate static point scatterers from OSM building contours inside a ROI.
%
% Inputs:
%   osmLocal          - structure generated by helperConvertOSMBuildingsToLocalXY
%   scenarioROI       - [xMin xMax; yMin yMax]
%   scattererSpacing  - approximate spacing between scatterers in meters
%
% Outputs:
%   scattererPositions       - 3 x N matrix: [x; y; z]
%   reflectionCoefficients   - 1 x N complex vector
%
% This function does not modify the ISAC framework. It only converts
% building contours into static point scatterers for later use.

    if nargin < 3 || isempty(scattererSpacing)
        scattererSpacing = 2; % meters
    end

    xMin = scenarioROI(1,1);
    xMax = scenarioROI(1,2);
    yMin = scenarioROI(2,1);
    yMax = scenarioROI(2,2);

    xScatterers = [];
    yScatterers = [];

    %% Loop over all buildings

    for iB = 1:numel(osmLocal.buildings)

        x = osmLocal.buildings(iB).x(:);
        y = osmLocal.buildings(iB).y(:);

        % NaNs separate different polygon rings or holes.
        valid = ~isnan(x) & ~isnan(y);

        if ~any(valid)
            continue;
        end

        % Split the contour into continuous parts separated by NaNs.
        nanIdx = find(~valid);
        splitIdx = [0; nanIdx; numel(x)+1];

        for iPart = 1:numel(splitIdx)-1

            idxStart = splitIdx(iPart) + 1;
            idxEnd   = splitIdx(iPart+1) - 1;

            if idxEnd - idxStart + 1 < 2
                continue;
            end

            xPart = x(idxStart:idxEnd);
            yPart = y(idxStart:idxEnd);

            % Sample each edge of the polygon.
            for k = 1:numel(xPart)-1

                p1 = [xPart(k);   yPart(k)];
                p2 = [xPart(k+1); yPart(k+1)];

                edgeLength = norm(p2 - p1);

                if edgeLength == 0
                    continue;
                end

                % Number of points along this edge.
                numPts = max(2, ceil(edgeLength / scattererSpacing) + 1);

                alpha = linspace(0, 1, numPts);

                xEdge = p1(1) + alpha * (p2(1) - p1(1));
                yEdge = p1(2) + alpha * (p2(2) - p1(2));

                % Keep only scatterers inside the selected ROI.
                insideROI = xEdge >= xMin & xEdge <= xMax & ...
                            yEdge >= yMin & yEdge <= yMax;

                xScatterers = [xScatterers, xEdge(insideROI)]; %#ok<AGROW>
                yScatterers = [yScatterers, yEdge(insideROI)]; %#ok<AGROW>

            end
        end
    end

    %% Remove duplicated scatterers caused by shared vertices

    if isempty(xScatterers)
        warning("No scatterers were generated inside the selected ROI.");
        scattererPositions = zeros(3,0);
        reflectionCoefficients = zeros(1,0);
        return;
    end

    points = [xScatterers(:), yScatterers(:)];

    % Round slightly to avoid near-duplicates due to numerical precision.
    pointsRounded = round(points, 3);
    [pointsUnique, ~] = unique(pointsRounded, "rows", "stable");

    xScatterers = pointsUnique(:,1).';
    yScatterers = pointsUnique(:,2).';

    %% Build scatterer output

    zScatterers = zeros(size(xScatterers)); % 2D case for now

    scattererPositions = [xScatterers;
                          yScatterers;
                          zScatterers];

    % Simple complex reflection coefficients.
    % Fixed random seed for reproducibility.
    rng(1);
    reflectionMagnitude = 1.0;
    reflectionCoefficients = reflectionMagnitude * exp(1j * 2*pi*rand(1, size(scattererPositions,2)));

    %% Validation plot

    figure("Name", "OSM building scatterers inside ROI");
    hold on;
    grid on;
    axis equal;

    % Plot original building contours
    %for iB = 1:numel(osmLocal.buildings)
       % plot(osmLocal.buildings(iB).x, osmLocal.buildings(iB).y, ...
           % "Color", [0.3 0.3 0.3], ...
           % "LineWidth", 1.0);
    %end

    % Plot generated scatterers
    plot(scattererPositions(1,:), scattererPositions(2,:), ...
        ".", "MarkerSize", 10);

    % Zoom to ROI
    xlim([xMin xMax]);
    ylim([yMin yMax]);

    xlabel("x (m)");
    ylabel("y (m)");
    title(sprintf("Static scatterers generated from OSM building contours - %d points", size(scattererPositions,2)));

    legend("Building contours", "Generated scatterers", "Location", "bestoutside");

    hold off;

    fprintf("Generated %d static scatterers inside ROI.\n", size(scattererPositions,2));
    fprintf("Scatterer spacing: %.2f m\n", scattererSpacing);

end

%[appendix]{"version":"1.0"}
%---
