function fig = helperPlotSpeedEstimationResults( ...
    simulationTime, ...
    trajectories, ...
    targetStateEstimates, ...
    trackIDs, ...
    scenarioName, ...
    topology, ...
    config)
%HELPERPLOTSPEEDESTIMATIONRESULTS Plot speed and heading estimates.

    fig = figure( ...
        'Color', 'w', ...
        'Name', 'Speed and Heading Estimates', ...
        'NumberTitle', 'off');

    layout = tiledlayout( ...
        fig, ...
        1, ...
        2, ...
        'Padding', 'compact', ...
        'TileSpacing', 'compact');

    %% Speed axes

    speedAxes = nexttile(layout);

    hold(speedAxes, 'on');
    grid(speedAxes, 'on');
    box(speedAxes, 'on');

    xlabel(speedAxes, 'Time [s]');
    ylabel(speedAxes, 'Speed [m/s]');
    title(speedAxes, 'Speed');

    xlim(speedAxes, ...
        [simulationTime(1), simulationTime(end)]);

    %% Heading axes

    headingAxes = nexttile(layout);

    hold(headingAxes, 'on');
    grid(headingAxes, 'on');
    box(headingAxes, 'on');

    xlabel(headingAxes, 'Time [s]');
    ylabel(headingAxes, 'Heading [deg]');
    title(headingAxes, 'Heading');

    xlim(headingAxes, ...
        [simulationTime(1), simulationTime(end)]);

    ylim(headingAxes, [-180 180]);

    %% Track estimates

    for trackIndex = 1:numel(trackIDs)

        trackID = trackIDs(trackIndex);

        velocityX = targetStateEstimates( ...
            2, :, trackID);

        velocityY = targetStateEstimates( ...
            4, :, trackID);

        speedEstimate = sqrt( ...
            velocityX.^2 + velocityY.^2);

        headingEstimate = atan2d( ...
            velocityY, velocityX);

        plot( ...
            speedAxes, ...
            simulationTime, ...
            speedEstimate, ...
            's--', ...
            'LineWidth', 1.6, ...
            'DisplayName', sprintf( ...
                'Track %d estimate', trackID));

        plot( ...
            headingAxes, ...
            simulationTime, ...
            headingEstimate, ...
            's--', ...
            'LineWidth', 1.6, ...
            'DisplayName', sprintf( ...
                'Track %d estimate', trackID));
    end

    %% Ground truth

    for targetIndex = 1:numel(trajectories)

        [~, ~, velocity] = lookupPose( ...
            trajectories{targetIndex}, ...
            simulationTime);

        trueSpeed = sqrt( ...
            velocity(:, 1).^2 ...
            + velocity(:, 2).^2);

        trueHeading = atan2d( ...
            velocity(:, 2), ...
            velocity(:, 1));

        plot( ...
            speedAxes, ...
            simulationTime, ...
            trueSpeed, ...
            '-', ...
            'LineWidth', 1.8, ...
            'DisplayName', sprintf( ...
                'Target %d truth', targetIndex));

        plot( ...
            headingAxes, ...
            simulationTime, ...
            trueHeading, ...
            '-', ...
            'LineWidth', 1.8, ...
            'DisplayName', sprintf( ...
                'Target %d truth', targetIndex));
    end

    legend(speedAxes, ...
        'Location', 'best');

    legend(headingAxes, ...
        'Location', 'best');

    sgtitle( ...
        fig, ...
        sprintf( ...
            'Speed and heading - %s / %s', ...
            scenarioName, ...
            topology), ...
        'Interpreter', 'none');

    %% Optional export

    if config.exportFigures

        if ~isfolder(config.outputDirectory)
            mkdir(config.outputDirectory);
        end

        outputName = sprintf( ...
            '%s_%s_speed_heading.pdf', ...
            lower(char(scenarioName)), ...
            lower(char(topology)));

        exportgraphics( ...
            fig, ...
            fullfile(config.outputDirectory, outputName), ...
            'ContentType', 'vector', ...
            'BackgroundColor', 'white');
    end
end