function ISACSimulationApp
%ISACSIMULATIONAPP Graphical interface for the ISAC simulation framework.
%
%   The application allows the user to:
%       - Select the scenario and sensing topology
%       - Select the target trajectory case
%       - Configure main simulation parameters
%       - Run the ISAC simulation
%       - Inspect the final Cartesian and Range-AoA frames
%       - Review summary metrics
%       - Open the interactive playback viewer
%       - Export the stored frames as a video

    %% Application state

    appResults = [];

    %% Main window

    appFigure = figure( ...
        'Name', 'ISAC Simulation Framework', ...
        'NumberTitle', 'off', ...
        'Color', 'w', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'Position', [40 40 1500 850], ...
        'CloseRequestFcn', @closeApplication);

    %% Configuration panel

    configurationPanel = uipanel( ...
        'Parent', appFigure, ...
        'Title', 'Simulation configuration', ...
        'FontWeight', 'bold', ...
        'Units', 'normalized', ...
        'Position', [0.015 0.05 0.225 0.90]);

    createPanelLabel( ...
        configurationPanel, ...
        'Scenario', ...
        [0.08 0.895 0.84 0.04]);

    scenarioPopup = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.845 0.84 0.055], ...
        'String', { ...
            'baseline', ...
            'openArea', ...
            'piotrkowskaStreetCanyon'}, ...
        'Value', 1, ...
        'Callback', @scenarioChanged);

    createPanelLabel( ...
        configurationPanel, ...
        'Sensing topology', ...
        [0.08 0.775 0.84 0.04]);

    topologyPopup = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.725 0.84 0.055], ...
        'String', {'monostatic', 'bistatic'}, ...
        'Value', 1);

    createPanelLabel( ...
        configurationPanel, ...
        'Target trajectory case', ...
        [0.08 0.655 0.84 0.04]);

    targetCasePopup = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.605 0.84 0.055], ...
        'String', {'twoTargetsOriginalFast'}, ...
        'Value', 1);

    createPanelLabel( ...
        configurationPanel, ...
        'Random seed', ...
        [0.08 0.535 0.42 0.04]);

    randomSeedEdit = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.53 0.525 0.39 0.055], ...
        'String', '0', ...
        'BackgroundColor', 'w');

    createPanelLabel( ...
        configurationPanel, ...
        'Time step dt [s]', ...
        [0.08 0.465 0.42 0.04]);

    timeStepEdit = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.53 0.455 0.39 0.055], ...
        'String', '0.4', ...
        'BackgroundColor', 'w');

    createPanelLabel( ...
        configurationPanel, ...
        'Sensing frames', ...
        [0.08 0.395 0.42 0.04]);

    numFramesEdit = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.53 0.385 0.39 0.055], ...
        'String', '10', ...
        'BackgroundColor', 'w');

    createPanelLabel( ...
        configurationPanel, ...
        'CFAR probability', ...
        [0.08 0.325 0.42 0.04]);

    cfarPfaEdit = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.53 0.315 0.39 0.055], ...
        'String', '1e-5', ...
        'BackgroundColor', 'w');

    autoExtendCheckbox = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'checkbox', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.255 0.84 0.045], ...
        'String', 'Auto-extend slow cases to 20 frames', ...
        'Value', 1);

    showInitialScenarioCheckbox = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'checkbox', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.205 0.84 0.045], ...
        'String', 'Show initial scenario figure', ...
        'Value', 0);

    showTrackingErrorCheckbox = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'checkbox', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.155 0.84 0.045], ...
        'String', 'Show tracking error figure', ...
        'Value', 0);

    showSpeedHeadingCheckbox = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'checkbox', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.105 0.84 0.045], ...
        'String', 'Show speed and heading figure', ...
        'Value', 0);

    printSummaryCheckbox = uicontrol( ...
        'Parent', configurationPanel, ...
        'Style', 'checkbox', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.055 0.84 0.045], ...
        'String', 'Print metrics in command window', ...
        'Value', 1);

    %% Cartesian scenario axes

    scenarioAxes = axes( ...
        'Parent', appFigure, ...
        'Units', 'normalized', ...
        'Position', [0.285 0.555 0.30 0.36]);

    title(scenarioAxes, 'Cartesian scenario');
    xlabel(scenarioAxes, 'x [m]');
    ylabel(scenarioAxes, 'y [m]');

    grid(scenarioAxes, 'on');
    box(scenarioAxes, 'on');

    %% Range-AoA axes

    rangeAoAAxes = axes( ...
        'Parent', appFigure, ...
        'Units', 'normalized', ...
        'Position', [0.65 0.555 0.30 0.36]);

    title(rangeAoAAxes, 'Range-AoA map');
    xlabel(rangeAoAAxes, 'AoA [deg]');
    ylabel(rangeAoAAxes, 'Range [m]');

    grid(rangeAoAAxes, 'on');
    box(rangeAoAAxes, 'on');

    colormap(rangeAoAAxes, gray(256));

    %% Metrics panel

    metricsPanel = uipanel( ...
        'Parent', appFigure, ...
        'Title', 'Simulation metrics', ...
        'FontWeight', 'bold', ...
        'Units', 'normalized', ...
        'Position', [0.265 0.05 0.345 0.42]);

    metricsText = uicontrol( ...
        'Parent', metricsPanel, ...
        'Style', 'edit', ...
        'Units', 'normalized', ...
        'Position', [0.04 0.05 0.92 0.90], ...
        'Max', 30, ...
        'Min', 0, ...
        'Enable', 'inactive', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', 'w', ...
        'FontName', 'Consolas', ...
        'String', { ...
            'No simulation results available.', ...
            '', ...
            'Configure the simulation and press Run Simulation.'});

    %% Actions panel

    actionsPanel = uipanel( ...
        'Parent', appFigure, ...
        'Title', 'Simulation control', ...
        'FontWeight', 'bold', ...
        'Units', 'normalized', ...
        'Position', [0.63 0.05 0.345 0.42]);

    runButton = uicontrol( ...
        'Parent', actionsPanel, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.75 0.84 0.14], ...
        'String', 'Run Simulation', ...
        'FontWeight', 'bold', ...
        'FontSize', 11, ...
        'Callback', @runSimulation);

    playbackButton = uicontrol( ...
        'Parent', actionsPanel, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.56 0.40 0.12], ...
        'String', 'Open Playback', ...
        'Enable', 'off', ...
        'Callback', @openPlayback);

    exportButton = uicontrol( ...
        'Parent', actionsPanel, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.52 0.56 0.40 0.12], ...
        'String', 'Export Video', ...
        'Enable', 'off', ...
        'Callback', @exportVideo);

    resetButton = uicontrol( ...
        'Parent', actionsPanel, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.39 0.84 0.10], ...
        'String', 'Reset Application', ...
        'Callback', @resetApplication);

    statusLabel = uicontrol( ...
        'Parent', actionsPanel, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.16 0.84 0.14], ...
        'String', 'Ready', ...
        'HorizontalAlignment', 'center', ...
        'FontWeight', 'bold', ...
        'BackgroundColor', get(actionsPanel, 'BackgroundColor'));

    statusDetails = uicontrol( ...
        'Parent', actionsPanel, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.08 0.04 0.84 0.10], ...
        'String', 'Select a configuration and run the simulation.', ...
        'HorizontalAlignment', 'center', ...
        'BackgroundColor', get(actionsPanel, 'BackgroundColor'));

    %% Initialise target cases

    updateTargetCases();

    %% Callbacks

    function scenarioChanged(~, ~)

        updateTargetCases();
    end

    function updateTargetCases()

        scenarioName = getPopupValue(scenarioPopup);

        if scenarioName == "piotrkowskaStreetCanyon"

            targetCases = { ...
                'singleT1Fast', ...
                'singleT1Slow', ...
                'singleT2Slow', ...
                'twoTargetsOriginalFast', ...
                'twoTargetsOriginalSlow', ...
                'twoTargetsSeparatedSlow'};

        else

            targetCases = { ...
                'twoTargetsOriginalFast'};
        end

        set( ...
            targetCasePopup, ...
            'String', targetCases, ...
            'Value', 1);
    end

    function runSimulation(~, ~)

        try

            config = buildConfiguration();

        catch exception

            errordlg( ...
                exception.message, ...
                'Invalid configuration');

            return;
        end

        setApplicationRunning(true);

        set(statusLabel, ...
            'String', 'Running simulation...');

        set(statusDetails, ...
            'String', sprintf( ...
                '%s / %s', ...
                config.scenarioName, ...
                config.topology));

        set(appFigure, 'Pointer', 'watch');

        drawnow;

        try

            appResults = runISACSimulation(config);

            finalFrame = numel(appResults.frames);

            renderISACFrame( ...
                scenarioAxes, ...
                rangeAoAAxes, ...
                appResults, ...
                finalFrame);

            updateMetricsPanel();

            set(statusLabel, ...
                'String', 'Simulation completed');

            set(statusDetails, ...
                'String', sprintf( ...
                    '%d frames processed successfully.', ...
                    finalFrame));

        catch exception

            appResults = [];

            cla(scenarioAxes);
            cla(rangeAoAAxes);

            set(metricsText, ...
                'String', { ...
                    'Simulation failed.', ...
                    '', ...
                    exception.message});

            set(statusLabel, ...
                'String', 'Simulation failed');

            set(statusDetails, ...
                'String', exception.message);

            errordlg( ...
                getReport(exception, 'extended'), ...
                'ISAC simulation error');
        end

        set(appFigure, 'Pointer', 'arrow');

        setApplicationRunning(false);

        drawnow;
    end

    function config = buildConfiguration()

        config = defaultConfig();

        config.scenarioName = ...
            getPopupValue(scenarioPopup);

        config.topology = ...
            getPopupValue(topologyPopup);

        config.targetCase = ...
            getPopupValue(targetCasePopup);

        randomSeed = str2double( ...
            get(randomSeedEdit, 'String'));

        timeStep = str2double( ...
            get(timeStepEdit, 'String'));

        numFrames = str2double( ...
            get(numFramesEdit, 'String'));

        cfarPfa = str2double( ...
            get(cfarPfaEdit, 'String'));

        if ~isfinite(randomSeed) ...
                || randomSeed < 0 ...
                || randomSeed ~= round(randomSeed)

            error( ...
                "Random seed must be a non-negative integer.");
        end

        if ~isfinite(timeStep) || timeStep <= 0

            error( ...
                "Time step dt must be greater than zero.");
        end

        if ~isfinite(numFrames) ...
                || numFrames < 1 ...
                || numFrames ~= round(numFrames)

            error( ...
                "Number of sensing frames must be a positive integer.");
        end

        if ~isfinite(cfarPfa) ...
                || cfarPfa <= 0 ...
                || cfarPfa >= 1

            error( ...
                "CFAR probability must be between zero and one.");
        end

        config.randomSeed = round(randomSeed);
        config.dt = timeStep;
        config.numSensingFrames = round(numFrames);
        config.cfarPfa = cfarPfa;

        config.autoExtendSlowTargetCases = logical( ...
            get(autoExtendCheckbox, 'Value'));

        config.showInitialScenario = logical( ...
            get(showInitialScenarioCheckbox, 'Value'));

        config.showTrackingErrorFigure = logical( ...
            get(showTrackingErrorCheckbox, 'Value'));

        config.showSpeedHeadingFigure = logical( ...
            get(showSpeedHeadingCheckbox, 'Value'));

        config.printMetricsSummary = logical( ...
            get(printSummaryCheckbox, 'Value'));

        % The app and the external playback replace the old live figure.
        config.showLiveAnimation = false;
        config.showResourceGrid = false;

        % Frames are always required by the app.
        config.storePlaybackFrames = true;

        % Export is performed from the Export Video button.
        config.exportFigures = false;
        config.exportVideo = false;
    end

    function updateMetricsPanel()

        targetTruthText = formatVector( ...
            100 * appResults.targetTruthHitRate, ...
            '%.2f');

        targetTrackText = formatVector( ...
            100 * appResults.targetTrackHitRate, ...
            '%.2f');

        positionErrorText = formatVector( ...
            appResults.meanTrackPositionError, ...
            '%.3f');

        metricsLines = { ...
            sprintf('Scenario: %s', ...
                char(appResults.scenarioName)), ...
            sprintf('Topology: %s', ...
                char(appResults.topology)), ...
            sprintf('Target case: %s', ...
                char(appResults.targetCase)), ...
            '', ...
            sprintf('Frames: %d', ...
                numel(appResults.frames)), ...
            sprintf('Mean clustered detections: %.2f', ...
                appResults.meanNumDetections), ...
            sprintf('Mean raw CFAR detections: %.2f', ...
                appResults.meanNumRawCFARDetections), ...
            sprintf('Mean active tracks: %.2f', ...
                appResults.meanNumTracks), ...
            sprintf('Total Track IDs: %d', ...
                appResults.totalTrackIDs), ...
            sprintf('Approximate extra tracks: %d', ...
                appResults.totalFalseTracks), ...
            '', ...
            sprintf('Mean truth hit rate: %.2f %%', ...
                100 * appResults.meanTruthHitRate), ...
            sprintf('Target truth hit rates [%%]: %s', ...
                targetTruthText), ...
            sprintf('Mean track hit rate: %.2f %%', ...
                100 * appResults.meanTrackHitRate), ...
            sprintf('Track hit without initial frame: %.2f %%', ...
                100 * appResults.meanTrackHitRateNoInit), ...
            sprintf('Previous-frame truth hit rate: %.2f %%', ...
                100 * appResults.meanTrackHitRatePrevTruth), ...
            sprintf('Target track hit rates [%%]: %s', ...
                targetTrackText), ...
            sprintf('Mean target position errors [m]: %s', ...
                positionErrorText)};

        set(metricsText, ...
            'String', metricsLines);
    end

    function openPlayback(~, ~)

        if isempty(appResults)
            return;
        end

        playISACResults(appResults);
    end

    function exportVideo(~, ~)

        if isempty(appResults)
            return;
        end

        defaultVideoName = sprintf( ...
            '%s_%s_playback.avi', ...
            char(appResults.scenarioName), ...
            char(appResults.topology));

        [fileName, folderName] = uiputfile( ...
            '*.avi', ...
            'Export ISAC video', ...
            defaultVideoName);

        if isequal(fileName, 0)
            return;
        end

        videoConfig = appResults.config;

        videoConfig.outputDirectory = ...
            string(folderName);

        videoConfig.videoFileName = ...
            string(fileName);

        set(exportButton, 'Enable', 'off');

        set(statusLabel, ...
            'String', 'Exporting video...');

        set(statusDetails, ...
            'String', 'Rendering stored simulation frames.');

        set(appFigure, 'Pointer', 'watch');

        drawnow;

        try

            videoPath = exportISACVideo( ...
                appResults, ...
                videoConfig);

            set(statusLabel, ...
                'String', 'Video exported');

            set(statusDetails, ...
                'String', char(videoPath));

            msgbox( ...
                sprintf( ...
                    'Video exported successfully:\n%s', ...
                    videoPath), ...
                'Video export');

        catch exception

            set(statusLabel, ...
                'String', 'Video export failed');

            set(statusDetails, ...
                'String', exception.message);

            errordlg( ...
                getReport(exception, 'extended'), ...
                'Video export error');
        end

        set(appFigure, 'Pointer', 'arrow');

        if ~isempty(appResults)
            set(exportButton, 'Enable', 'on');
        end
    end

    function resetApplication(~, ~)

        appResults = [];

        set(scenarioPopup, 'Value', 1);
        set(topologyPopup, 'Value', 1);

        updateTargetCases();

        set(randomSeedEdit, 'String', '0');
        set(timeStepEdit, 'String', '0.4');
        set(numFramesEdit, 'String', '10');
        set(cfarPfaEdit, 'String', '1e-5');

        set(autoExtendCheckbox, 'Value', 1);
        set(showInitialScenarioCheckbox, 'Value', 0);
        set(showTrackingErrorCheckbox, 'Value', 0);
        set(showSpeedHeadingCheckbox, 'Value', 0);
        set(printSummaryCheckbox, 'Value', 1);

        cla(scenarioAxes);
        cla(rangeAoAAxes);

        title(scenarioAxes, 'Cartesian scenario');
        xlabel(scenarioAxes, 'x [m]');
        ylabel(scenarioAxes, 'y [m]');

        title(rangeAoAAxes, 'Range-AoA map');
        xlabel(rangeAoAAxes, 'AoA [deg]');
        ylabel(rangeAoAAxes, 'Range [m]');

        grid(scenarioAxes, 'on');
        grid(rangeAoAAxes, 'on');

        set(metricsText, ...
            'String', { ...
                'No simulation results available.', ...
                '', ...
                'Configure the simulation and press Run Simulation.'});

        set(playbackButton, 'Enable', 'off');
        set(exportButton, 'Enable', 'off');

        set(statusLabel, 'String', 'Ready');

        set(statusDetails, ...
            'String', ...
            'Select a configuration and run the simulation.');
    end

    function setApplicationRunning(isRunning)

        configurationControls = [ ...
            scenarioPopup, ...
            topologyPopup, ...
            targetCasePopup, ...
            randomSeedEdit, ...
            timeStepEdit, ...
            numFramesEdit, ...
            cfarPfaEdit, ...
            autoExtendCheckbox, ...
            showInitialScenarioCheckbox, ...
            showTrackingErrorCheckbox, ...
            showSpeedHeadingCheckbox, ...
            printSummaryCheckbox];

        if isRunning

            set(configurationControls, 'Enable', 'off');

            set(runButton, 'Enable', 'off');
            set(playbackButton, 'Enable', 'off');
            set(exportButton, 'Enable', 'off');
            set(resetButton, 'Enable', 'off');

        else

            set(configurationControls, 'Enable', 'on');

            set(runButton, 'Enable', 'on');
            set(resetButton, 'Enable', 'on');

            if isempty(appResults)

                set(playbackButton, 'Enable', 'off');
                set(exportButton, 'Enable', 'off');

            else

                set(playbackButton, 'Enable', 'on');
                set(exportButton, 'Enable', 'on');
            end
        end
    end

    function value = getPopupValue(controlHandle)

        items = get(controlHandle, 'String');
        selectedIndex = get(controlHandle, 'Value');

        if ischar(items)

            value = string( ...
                strtrim(items(selectedIndex, :)));

        else

            value = string( ...
                items{selectedIndex});
        end
    end

    function outputText = formatVector(values, formatSpecification)

        values = values(:).';

        components = arrayfun( ...
            @(value) sprintf(formatSpecification, value), ...
            values, ...
            'UniformOutput', false);

        outputText = strjoin(components, ', ');
    end

    function createPanelLabel(parentHandle, labelText, position)

        uicontrol( ...
            'Parent', parentHandle, ...
            'Style', 'text', ...
            'Units', 'normalized', ...
            'Position', position, ...
            'String', labelText, ...
            'HorizontalAlignment', 'left', ...
            'FontWeight', 'bold', ...
            'BackgroundColor', ...
                get(parentHandle, 'BackgroundColor'));
    end

    function closeApplication(~, ~)

        if isgraphics(appFigure)
            delete(appFigure);
        end
    end
end