function results = runISACSimulation(config)
%RUNISACSIMULATION Run the configurable ISAC simulation.
%
%   RESULTS = RUNISACSIMULATION(CONFIG) prepares and executes the ISAC
%   simulation using the supplied configuration.
%
%   RESULTS = RUNISACSIMULATION() uses defaultConfig.

    %% Input configuration

    if nargin < 1 || isempty(config)
        config = defaultConfig();
    end

    validateattributes(config, {'struct'}, {'scalar'});

    config.scenarioName = string(config.scenarioName);
    config.topology = string(config.topology);
    config.targetCase = string(config.targetCase);

    validScenarios = [
        "baseline"
        "openArea"
        "piotrkowskaStreetCanyon"
    ];

    validTopologies = [
        "monostatic"
        "bistatic"
    ];

    if ~any(config.scenarioName == validScenarios)
        error("Unknown scenario: %s", config.scenarioName);
    end

    if ~any(config.topology == validTopologies)
        error("Unknown topology: %s", config.topology);
    end

    %% Reproducibility

    rng(config.randomSeed, "twister");

    %% Carrier configuration

    carrierFrequency = config.carrierFrequency;
    wavelength = freq2wavelen(carrierFrequency);

    %% Scenario-dependent geometry

    scenarioConfig = helperGetScenarioConfig( ...
        config.scenarioName, ...
        config.topology);

    % Use file paths defined in defaultConfig.
    switch config.scenarioName

        case "openArea"
            scenarioConfig.scattererMatFile = ...
                config.openAreaScattererFile;

        case "piotrkowskaStreetCanyon"
            scenarioConfig.scattererMatFile = ...
                config.piotrkowskaScattererFile;
    end

    txPosition = scenarioConfig.txPosition;
    rxPosition = scenarioConfig.rxPosition;

    txOrientationAxes = scenarioConfig.txOrientationAxes;
    rxOrientationAxes = scenarioConfig.rxOrientationAxes;

    regionOfInterest = scenarioConfig.roi;

    fprintf("\nISAC simulation setup\n");
    fprintf("Scenario: %s\n", config.scenarioName);
    fprintf("Topology: %s\n", config.topology);

    fprintf( ...
        "Tx position: [%.1f %.1f %.1f] m\n", ...
        txPosition(1), ...
        txPosition(2), ...
        txPosition(3));

    fprintf( ...
        "Rx position: [%.1f %.1f %.1f] m\n", ...
        rxPosition(1), ...
        rxPosition(2), ...
        rxPosition(3));

    %% Plot limits

    plotMargin = 10;

    scenarioPlotXLim = [
        regionOfInterest(1, 1) - plotMargin
        regionOfInterest(1, 2) + plotMargin
    ];

    scenarioPlotYLim = [
        regionOfInterest(2, 1) - plotMargin
        regionOfInterest(2, 2) + plotMargin
    ];

    %% Transmitter

    transmitter = phased.Transmitter( ...
        'PeakPower', db2pow(config.txPowerDBm - 30), ...
        'Gain', 0);

    numTxAntennas = config.numTxAntennas;

    element = phased.IsotropicAntennaElement( ...
        'BackBaffled', true);

    txArray = phased.ULA( ...
        numTxAntennas, ...
        wavelength / 2, ...
        'Element', element);

    %% Receiver

    receiver = phased.Receiver( ...
        'AddInputNoise', true, ...
        'Gain', 0, ...
        'NoiseMethod', 'Noise figure', ...
        'NoiseFigure', config.receiverNoiseFigureDB, ...
        'ReferenceTemperature', config.referenceTemperatureK);

    switch config.topology

        case "bistatic"

            numRxAntennas = config.numRxAntennas;

            rxArray = phased.ULA( ...
                numRxAntennas, ...
                wavelength / 2, ...
                'Element', element);

        case "monostatic"

            % Preserve the original monostatic implementation:
            % the same physical array is used for transmission and reception.
            numRxAntennas = numTxAntennas;
            rxArray = txArray;
    end

    %% Static scatterers

    if scenarioConfig.useOSMScatterers

        scattererFile = scenarioConfig.scattererMatFile;

        if ~isfile(scattererFile)
            error( ...
                "OSM scatterer file not found: %s", ...
                scattererFile);
        end

        scattererData = load( ...
            scattererFile, ...
            "scattererPositions", ...
            "reflectionCoefficients");

        requiredFields = [
            "scattererPositions"
            "reflectionCoefficients"
        ];

        for fieldIndex = 1:numel(requiredFields)

            fieldName = requiredFields(fieldIndex);

            if ~isfield(scattererData, fieldName)
                error( ...
                    "Variable %s not found in %s.", ...
                    fieldName, ...
                    scattererFile);
            end
        end

        scatterers.Positions = ...
            scattererData.scattererPositions;

        scatterers.ReflectionCoefficients = ...
            scattererData.reflectionCoefficients ...
            .* config.osmReflectionScale;

    else

        [scatterers.Positions, ...
            scatterers.ReflectionCoefficients] = ...
            helperGenerateStaticScatterers( ...
                config.numBaselineScatterers, ...
                regionOfInterest);
    end

    scatterers.Velocities = ...
        zeros(size(scatterers.Positions));

    numScatterers = size(scatterers.Positions, 2);

    fprintf( ...
        "Number of static scatterers: %d\n", ...
        numScatterers);

    %% Targets and trajectories

    targets.Trajectories = ...
        helperGetTargetTrajectories( ...
            config.scenarioName, ...
            config.targetCase);

    numTargets = numel(targets.Trajectories);

    targets.ReflectionCoefficients = ...
        exp(1i * 2 * pi * rand(1, numTargets));

    fprintf("Number of targets: %d\n", numTargets);

    %% Scattering channel

    simulateDirectPath = ...
        config.topology == "bistatic";

    channel = phased.ScatteringMIMOChannel( ...
        'CarrierFrequency', carrierFrequency, ...
        'TransmitArray', txArray, ...
        'TransmitArrayPosition', txPosition, ...
        'ReceiveArray', rxArray, ...
        'ReceiveArrayPosition', rxPosition, ...
        'TransmitArrayOrientationAxes', txOrientationAxes, ...
        'ReceiveArrayOrientationAxes', rxOrientationAxes, ...
        'SimulateDirectPath', simulateDirectPath, ...
        'ScattererSpecificationSource', 'Input Port', ...
        'ChannelResponseOutputPort', true, ...
        'Polarization', 'None');

    %% Initial scenario figure

    if config.showInitialScenario

        helperVisualizeScatteringMIMOChannel( ...
            channel, ...
            scatterers.Positions, ...
            targets.Trajectories);

        title(sprintf( ...
            'ISAC Scenario — %s / %s', ...
            config.scenarioName, ...
            config.topology));
    end

    %% 5G NR waveform

    waveformConfig = helperGet5GWaveformConfiguration( ...
        config.channelBandwidthMHz, ...
        config.bandwidthOccupancy, ...
        config.subcarrierSpacingKHz);

    waveformInfo = nrOFDMInfo(waveformConfig.Carrier);

    transmissionBandwidth = ...
        config.subcarrierSpacingKHz * 1e3 ...
        * waveformConfig.Carrier.NSizeGrid ...
        * 12;

    channel.SampleRate = waveformInfo.SampleRate;

    %% Optional PDSCH DM-RS resource grid

    if config.showResourceGrid

        resourceGrid = nrResourceGrid( ...
            waveformConfig.Carrier, ...
            waveformConfig.PDSCH.NumLayers);

        dmrsIndices = nrPDSCHDMRSIndices( ...
            waveformConfig.Carrier, ...
            waveformConfig.PDSCH);

        dmrsSymbols = nrPDSCHDMRS( ...
            waveformConfig.Carrier, ...
            waveformConfig.PDSCH);

        resourceGrid(dmrsIndices) = dmrsSymbols;

        helperVisualizeResourceGrid( ...
            abs(resourceGrid(1:12, 1:14, 1)));

        title({ ...
            'PDSCH DM-RS Resource Elements', ...
            '(single resource block)'});
    end

    %% Maximum Doppler and velocity

    [~, pdschInfo] = nrPDSCHIndices( ...
        waveformConfig.Carrier, ...
        waveformConfig.PDSCH);

    Mt = max(diff(pdschInfo.DMRSSymbolSet));

    ofdmSymbolDuration = ...
        max(waveformInfo.SymbolLengths) ...
        / waveformInfo.SampleRate;

    maxDoppler = ...
        1 / (2 * Mt * ofdmSymbolDuration);

    maxVelocity = dop2speed( ...
        maxDoppler, ...
        wavelength);

    if config.topology == "monostatic"
        maxVelocity = maxVelocity / 2;
    end

    %% Maximum delay

    Mf = min(diff( ...
        waveformConfig.PDSCH.DMRS ...
        .DMRSSubcarrierLocations));

    maxDelay = ...
        1 / ( ...
        2 ...
        * Mf ...
        * config.subcarrierSpacingKHz ...
        * 1e3);

    channel.MaximumDelaySource = 'Property';
    channel.MaximumDelay = maxDelay;

    %% Range limits

    propagationSpeed = physconst("LightSpeed");

    if config.topology == "bistatic"

        baseline = vecnorm( ...
            txPosition - rxPosition);

        maxRange = ...
            maxDelay * propagationSpeed ...
            - baseline;

    else

        baseline = 0;

        maxRange = ...
            maxDelay * propagationSpeed / 2;
    end

    rangeResolution = ...
        propagationSpeed / transmissionBandwidth;

    if config.printSensingLimits

        fprintf( ...
            "Transmission bandwidth: %.2f MHz\n", ...
            transmissionBandwidth * 1e-6);

        fprintf( ...
            "Maximum unambiguous Doppler shift: %.2f kHz\n", ...
            maxDoppler * 1e-3);

        fprintf( ...
            "Maximum unambiguous velocity: %.2f m/s\n", ...
            maxVelocity);

        fprintf( ...
            "Maximum time delay: %.2f microseconds\n", ...
            maxDelay * 1e6);

        fprintf( ...
            "Maximum unambiguous %s range: %.2f m\n", ...
            config.topology, ...
            maxRange);

        fprintf( ...
            "Range resolution: %.2f m\n", ...
            rangeResolution);
    end

    %% Simulation time

    dt = config.dt;
    numSensingFrames = config.numSensingFrames;

    if config.autoExtendSlowTargetCases ...
            && contains(config.targetCase, "Slow")

        numSensingFrames = ...
            config.slowTargetNumFrames;
    end

    simulationTime = ...
        (0:numSensingFrames - 1) * dt;


        %% Range-AoA processing setup

    numAoA = ceil(2 * pi * numRxAntennas);

    aoaGrid = linspace( ...
        -90, ...
        90, ...
        numAoA);

    rxSteeringVector = phased.SteeringVector( ...
        SensorArray=channel.ReceiveArray);

    rxSteeringMatrix = rxSteeringVector( ...
        carrierFrequency, ...
        aoaGrid);

    %% AoD processing setup

    numAoD = ceil(2 * pi * numTxAntennas);

    aodGrid = linspace( ...
        -90, ...
        90, ...
        numAoD);

    txSteeringVector = phased.SteeringVector( ...
        SensorArray=channel.TransmitArray);

    txSteeringMatrix = txSteeringVector( ...
        carrierFrequency, ...
        aodGrid);

    %% Range grid

    rangeStep = ...
        rangeResolution ...
        / config.rangeOversamplingFactor;

    switch config.topology

        case "bistatic"

            rangeLimits = ...
                config.bistaticRangeLimits;

            rangeGrid = ...
                rangeLimits(1):rangeStep:rangeLimits(2);

            rangeFFTBins = ...
                (rangeGrid + baseline) ...
                / rangeResolution;

        case "monostatic"

            rangeLimits = ...
                config.monostaticRangeLimits;

            rangeGrid = ...
                rangeLimits(1):rangeStep:rangeLimits(2);

            rangeFFTBins = ...
                2 * rangeGrid ...
                / rangeResolution;
    end

    if numel(rangeGrid) < 2
        error( ...
            "The configured range grid must contain at least two points.");
    end

    numRange = numel(rangeGrid);

    %% Range steering matrix

    numSubcarriers = ...
        waveformConfig.Carrier.NSizeGrid * 12;

    subcarrierIndices = ...
        (0:numSubcarriers - 1).';

    rangeSteeringMatrix = ...
        exp( ...
            2 * pi * 1i ...
            * subcarrierIndices ...
            * rangeFFTBins ...
            / numSubcarriers) ...
        / numSubcarriers;

    %% Angular resolution

    aoaResolution = ap2beamwidth( ...
        (numRxAntennas - 1) ...
        * channel.ReceiveArray.ElementSpacing, ...
        wavelength);

    %% CFAR guard cells

    numGuardCellsRange = ...
        ceil( ...
            rangeResolution ...
            / (rangeGrid(2) - rangeGrid(1))) ...
        + 1;

    numGuardCellsAoA = ...
        ceil( ...
            aoaResolution ...
            / (aoaGrid(2) - aoaGrid(1))) ...
        + 1;

    %% Two-dimensional CFAR detector

    cfar2D = phased.CFARDetector2D( ...
        'GuardBandSize', ...
            [numGuardCellsRange numGuardCellsAoA], ...
        'TrainingBandSize', ...
            config.cfarTrainingBandSize, ...
        'ProbabilityFalseAlarm', ...
            config.cfarPfa, ...
        'OutputFormat', ...
            'CUT result', ...
        'ThresholdOutputPort', ...
            false);

    cfarOffsetIndices = ...
        cfar2D.TrainingBandSize ...
        + cfar2D.GuardBandSize;

    validRangeIndices = ...
        cfarOffsetIndices(1) + 1: ...
        numel(rangeGrid) - cfarOffsetIndices(1);

    validAngleIndices = ...
        cfarOffsetIndices(2) + 1: ...
        numel(aoaGrid) - cfarOffsetIndices(2);

    if isempty(validRangeIndices) || isempty(validAngleIndices)
        error( ...
            ["The range-AoA grid is too small for the selected " ...
             "CFAR guard and training bands."]);
    end

    [rangeCUTIndices, angleCUTIndices] = ...
        meshgrid( ...
            validRangeIndices, ...
            validAngleIndices);

    cfarCUTIndices = [
        rangeCUTIndices(:).'
        angleCUTIndices(:).'
    ];

    %% DBSCAN clustering

    clusterer = clusterDBSCAN();

    %% Tracker configuration

    tracker = helperConfigureTrackerByTopology( ...
        config, ...
        txPosition, ...
        rxPosition, ...
        txOrientationAxes, ...
        rxOrientationAxes, ...
        rangeResolution, ...
        aoaResolution);

    %% Frame dimensions

    numSymbolsPerFrame = ...
        waveformInfo.SlotsPerFrame ...
        * waveformInfo.SymbolsPerSlot;

    %% Detection and tracking storage

    trackIDs = [];

    % This array will expand dynamically when new Track IDs appear.
    targetStateEstimates = ...
        NaN(4, numSensingFrames, 0);

    numDetectionsPerFrame = ...
        zeros(numSensingFrames, 1);

    numRawCFARDetectionsPerFrame = ...
        zeros(numSensingFrames, 1);

    numTracksPerFrame = ...
        zeros(numSensingFrames, 1);

    falseTracksPerFrame = ...
        zeros(numSensingFrames, 1);

    %% Truth and detection association storage

    truthRangeAoAPerFrame = ...
        cell(numSensingFrames, 1);

    clusteredDetectionsPerFrame = ...
        cell(numSensingFrames, 1);

    truthHitRatePerFrame = ...
        zeros(numSensingFrames, 1);

    targetHitMatrix = ...
        false(numSensingFrames, numTargets);

    %% Tracking error storage

    trackPositionErrorPerFrame = ...
        NaN(numSensingFrames, numTargets);

    trackHitMatrix = ...
        false(numSensingFrames, numTargets);

    targetPositionsHistory = ...
        NaN(numSensingFrames, numTargets, 3);

    trackPositionErrorPrevTruthPerFrame = ...
        NaN(numSensingFrames, numTargets);

    trackHitPrevTruthMatrix = ...
        false(numSensingFrames, numTargets);

    %% Target separation diagnostics

    truthRangeSeparationPerFrame = ...
        NaN(numSensingFrames, 1);

    truthAoASeparationPerFrame = ...
        NaN(numSensingFrames, 1);

    %% Range-AoA and track histories

    rangeAoAMapPerFrame = ...
        cell(numSensingFrames, 1);

    tracksRangeAoAPerFrame = ...
        cell(numSensingFrames, 1);

    trackHistoryPerFrame = ...
        cell(numSensingFrames, 1);

    measuredPositionsPerFrame = ...
        cell(numSensingFrames, 1);

    %% Playback frame storage

    if config.storePlaybackFrames

        frameTemplate = struct( ...
            'simulationTime', [], ...
            'targetPositions', [], ...
            'measuredPositions', [], ...
            'tracks', [], ...
            'rangeAoAMap', [], ...
            'truthRangeAoA', [], ...
            'clusteredDetections', [], ...
            'trackRangeAoA', []);

        playbackFrames = ...
            repmat( ...
                frameTemplate, ...
                numSensingFrames, ...
                1);

    else

        playbackFrames = struct([]);
    end
    %% Live visualization setup

    scenarioCFARResultsFigure = [];
    scenarioPlotter = [];
    cfarResultsVisualizer = [];

    if config.showLiveAnimation

        scenarioCFARResultsFigure = figure( ...
            'Color', 'w', ...
            'Name', 'ISAC Live Simulation', ...
            'NumberTitle', 'off');

        liveLayout = tiledlayout( ...
            scenarioCFARResultsFigure, ...
            1, ...
            2, ...
            'Padding', 'tight', ...
            'TileSpacing', 'tight');

        scenarioPlotter = ...
            helperTheaterPlotter(liveLayout);

        scenarioPlotter.plotTxAndRx( ...
            txPosition, ...
            rxPosition);

        scenarioPlotter.plotTrajectories( ...
            targets.Trajectories, ...
            simulationTime);

        scenarioPlotter.plotScatterers( ...
            scatterers.Positions);

        scenarioPlotter.title(sprintf( ...
            'ISAC Scenario - %s (%s)', ...
            config.scenarioName, ...
            config.topology));

        % At this point only the scenario axes exist.
        scenarioAxes = findobj( ...
            scenarioCFARResultsFigure, ...
            'Type', ...
            'Axes');

        if ~isempty(scenarioAxes)

            set( ...
                scenarioAxes(1), ...
                'XLim', scenarioPlotXLim(:).', ...
                'YLim', scenarioPlotYLim(:).');
        end

        cfarResultsVisualizer = ...
            helperCFARResultsVisualizer(liveLayout);

        cfarResultsVisualizer.xlabel( ...
            'AoA (degrees)');

        if config.topology == "bistatic"

            cfarResultsVisualizer.ylabel( ...
                'Bistatic range (m)');

        else

            cfarResultsVisualizer.ylabel( ...
                'Monostatic range (m)');
        end

        cfarResultsVisualizer.title( ...
            'Range-AoA and CFAR results');

        drawnow;
    end
        %% Frame-by-frame sensing simulation

    for frameIndex = 1:numSensingFrames

        currentTime = simulationTime(frameIndex);

        fprintf( ...
            "\nProcessing sensing frame %d of %d, t = %.1f s\n", ...
            frameIndex, ...
            numSensingFrames, ...
            currentTime);

        %% Simulate one 5G NR sensing frame

        sensingCSI = helperSimulateLinkSingleFrame( ...
            transmitter, ...
            receiver, ...
            channel, ...
            waveformConfig, ...
            scatterers, ...
            targets, ...
            currentTime);

        reset(channel);

        %% Obtain true target positions

        targetPositions = zeros(numTargets, 3);

        for targetIndex = 1:numTargets

            targetPositions(targetIndex, :) = lookupPose( ...
                targets.Trajectories{targetIndex}, ...
                currentTime);
        end

        targetPositionsHistory( ...
            frameIndex, :, :) = targetPositions;

        %% True range, AoA and AoD

        [trueReceiverRange, trueAoA] = rangeangle( ...
            targetPositions.', ...
            rxPosition, ...
            rxOrientationAxes);

        [trueTransmitterRange, trueAoD] = rangeangle( ...
            targetPositions.', ...
            txPosition, ...
            txOrientationAxes);

        if config.topology == "bistatic"

            trueMapRange = ...
                trueReceiverRange ...
                + trueTransmitterRange ...
                - baseline;

        else

            trueMapRange = trueReceiverRange;
        end

        trueRangeAoA = [
            trueMapRange(:).'
            trueAoA(1, :)
        ];

        truthRangeAoAPerFrame{frameIndex} = ...
            trueRangeAoA;

        %% Target separation diagnostic

        if numTargets == 2

            truthRangeSeparationPerFrame(frameIndex) = ...
                abs(trueMapRange(1) - trueMapRange(2));

            truthAoASeparationPerFrame(frameIndex) = ...
                abs(wrapTo180( ...
                    trueAoA(1, 1) - trueAoA(1, 2)));
        end

        %% Optional geometry diagnostics

        if config.debugGeometry

            for targetIndex = 1:numTargets

                fprintf( ...
                    ['Target %d: position=[%.1f %.1f %.1f] m, ' ...
                     'mapRange=%.2f m, AoA=%.2f deg, AoD=%.2f deg\n'], ...
                    targetIndex, ...
                    targetPositions(targetIndex, 1), ...
                    targetPositions(targetIndex, 2), ...
                    targetPositions(targetIndex, 3), ...
                    trueMapRange(targetIndex), ...
                    trueAoA(1, targetIndex), ...
                    trueAoD(1, targetIndex));
            end
        end

        %% Static component suppression

        processedCSI = fft(sensingCSI, [], 2);

        processedCSI(:, 1, :, :) = 0;

        processedCSI = ifft(processedCSI, [], 2);

        %% Tx spatial processing

        processedCSI = permute( ...
            processedCSI, ...
            [4 1 3 2]);

        processedCSI = ...
            txSteeringMatrix' ...
            * reshape( ...
                processedCSI, ...
                numTxAntennas, ...
                []);

        processedCSI = permute( ...
            reshape( ...
                processedCSI, ...
                numAoD, ...
                numSubcarriers, ...
                numRxAntennas, ...
                numSymbolsPerFrame), ...
            [2 3 1 4]);

        %% Range processing

        processedCSI = ...
            rangeSteeringMatrix.' ...
            * reshape( ...
                processedCSI, ...
                numSubcarriers, ...
                []);

        processedCSI = permute( ...
            reshape( ...
                processedCSI, ...
                numRange, ...
                numRxAntennas, ...
                numAoD, ...
                numSymbolsPerFrame), ...
            [2 1 3 4]);

        %% Rx spatial processing

        processedCSI = ...
            rxSteeringMatrix' ...
            * reshape( ...
                processedCSI, ...
                numRxAntennas, ...
                []);

        processedCSI = reshape( ...
            processedCSI, ...
            numAoA, ...
            numRange, ...
            []);

        sumRangeAoAMap = sqrt( ...
            sum(abs(processedCSI).^2, 3)).';

        rangeAoAMapPerFrame{frameIndex} = ...
            sumRangeAoAMap;

        %% CFAR detection

        cfarResult = cfar2D( ...
            sumRangeAoAMap, ...
            cfarCUTIndices);

        detectionIndices = ...
            cfarCUTIndices(:, cfarResult);

        numRawCFARDetectionsPerFrame(frameIndex) = ...
            size(detectionIndices, 2);

        detectionValues = [
            rangeGrid(detectionIndices(1, :))
            aoaGrid(detectionIndices(2, :))
        ];

        %% DBSCAN clustering

        if isempty(detectionValues)

            clusteredDetections = zeros(2, 0);

        else

            [~, clusterIDs] = ...
                clusterer(detectionValues.');

            uniqueClusterIDs = unique(clusterIDs);

            numClusters = numel(uniqueClusterIDs);

            clusteredDetections = ...
                zeros(2, numClusters);

            for clusterIndex = 1:numClusters

                clusterMembers = ...
                    clusterIDs == ...
                    uniqueClusterIDs(clusterIndex);

                clusteredDetections(:, clusterIndex) = ...
                    mean( ...
                        detectionValues(:, clusterMembers), ...
                        2);
            end
        end

        clusteredDetectionsPerFrame{frameIndex} = ...
            clusteredDetections;

        %% Detection-level truth association

        [truthHitRatePerFrame(frameIndex), ...
            targetHitMatrix(frameIndex, :)] = ...
            helperComputeFrameTruthHitRate( ...
                trueRangeAoA, ...
                clusteredDetections, ...
                config.truthRangeTolerance, ...
                config.truthAoATolerance);

        %% Format detections and update tracker

        trackerDetections = ...
            helperFormatDetectionsForTrackerByTopology( ...
                config.topology, ...
                clusteredDetections, ...
                currentTime, ...
                rangeResolution, ...
                aoaResolution);

        tracks = tracker(trackerDetections);

        trackHistoryPerFrame{frameIndex} = tracks;

        %% Convert detections to Cartesian positions

        measuredPositions = helperGetMeasuredPositions( ...
            config.topology, ...
            clusteredDetections, ...
            txPosition, ...
            rxPosition, ...
            rxOrientationAxes);

        measuredPositionsPerFrame{frameIndex} = ...
            measuredPositions;

        %% Convert tracks to range-AoA

        trackRangeAoA = zeros(2, numel(tracks));

        for trackIndex = 1:numel(tracks)

            trackState = tracks(trackIndex).State;

            trackPosition = [
                trackState(1)
                trackState(3)
                0
            ];

            [trackReceiverRange, trackAoA] = rangeangle( ...
                trackPosition, ...
                rxPosition, ...
                rxOrientationAxes);

            if config.topology == "bistatic"

                trackTransmitterRange = rangeangle( ...
                    trackPosition, ...
                    txPosition, ...
                    txOrientationAxes);

                trackMapRange = ...
                    trackReceiverRange ...
                    + trackTransmitterRange ...
                    - baseline;

            else

                trackMapRange = trackReceiverRange;
            end

            trackRangeAoA(:, trackIndex) = [
                trackMapRange
                trackAoA(1)
            ];
        end

        tracksRangeAoAPerFrame{frameIndex} = ...
            trackRangeAoA;

        %% Current-frame tracking error

        [trackPositionErrorPerFrame(frameIndex, :), ...
            trackHitMatrix(frameIndex, :)] = ...
            helperComputeTrackTruthError( ...
                tracks, ...
                targetPositions, ...
                config.trackDistanceTolerance);

        %% Previous-frame truth diagnostic

        if frameIndex > 1

            previousTargetPositions = squeeze( ...
                targetPositionsHistory( ...
                    frameIndex - 1, :, :));

            if numTargets == 1

                previousTargetPositions = reshape( ...
                    previousTargetPositions, ...
                    1, ...
                    3);
            end

            [trackPositionErrorPrevTruthPerFrame( ...
                frameIndex, :), ...
                trackHitPrevTruthMatrix( ...
                frameIndex, :)] = ...
                helperComputeTrackTruthError( ...
                    tracks, ...
                    previousTargetPositions, ...
                    config.trackDistanceTolerance);
        end

        %% Store track states

        for trackIndex = 1:numel(tracks)

            trackID = tracks(trackIndex).TrackID;

            currentTrackSlots = ...
                size(targetStateEstimates, 3);

            if trackID > currentTrackSlots

                targetStateEstimates( ...
                    :, :, currentTrackSlots + 1:trackID) = NaN;
            end

            targetStateEstimates( ...
                :, frameIndex, trackID) = ...
                tracks(trackIndex).State;

            trackIDs = union(trackIDs, trackID);
        end

        %% Frame-level counts

        numDetectionsPerFrame(frameIndex) = ...
            size(clusteredDetections, 2);

        numTracksPerFrame(frameIndex) = ...
            numel(tracks);

        falseTracksPerFrame(frameIndex) = ...
            max(0, ...
                numTracksPerFrame(frameIndex) ...
                - numTargets);

        %% Store frame for future App Designer playback

        if config.storePlaybackFrames

            playbackFrames(frameIndex).simulationTime = ...
                currentTime;

            playbackFrames(frameIndex).targetPositions = ...
                targetPositions;

            playbackFrames(frameIndex).measuredPositions = ...
                measuredPositions;

            playbackFrames(frameIndex).tracks = ...
                tracks;

            playbackFrames(frameIndex).rangeAoAMap = ...
                sumRangeAoAMap;

            playbackFrames(frameIndex).truthRangeAoA = ...
                trueRangeAoA;

            playbackFrames(frameIndex).clusteredDetections = ...
                clusteredDetections;

            playbackFrames(frameIndex).trackRangeAoA = ...
                trackRangeAoA;
        end

        %% Update live animation

        if config.showLiveAnimation

            scenarioPlotter.plotTargetPositions( ...
                targetPositions);

            scenarioPlotter.plotDetections( ...
                measuredPositions);

            scenarioPlotter.plotTracks( ...
                tracks);

            cfarResultsVisualizer.plotCFARImage( ...
                aoaGrid, ...
                rangeGrid, ...
                sumRangeAoAMap);

            cfarResultsVisualizer.plotTruth( ...
                trueRangeAoA);

            cfarResultsVisualizer.plotClusteredDetections( ...
                clusteredDetections);

            sgtitle( ...
                scenarioCFARResultsFigure, ...
                sprintf( ...
                    'Frame %d/%d - Time %.1f s - %s / %s', ...
                    frameIndex, ...
                    numSensingFrames, ...
                    currentTime, ...
                    config.scenarioName, ...
                    config.topology), ...
                'FontSize', ...
                10);

            drawnow;
        end
    end
    %% Final metrics

    totalTrackIDs = numel(trackIDs);

    meanNumDetections = mean( ...
        numDetectionsPerFrame);

    meanNumRawCFARDetections = mean( ...
        numRawCFARDetectionsPerFrame);

    meanNumTracks = mean( ...
        numTracksPerFrame);

    totalFalseTracks = sum( ...
        falseTracksPerFrame);

    meanFalseTracksPerFrame = mean( ...
        falseTracksPerFrame);

    %% Detection-level metrics

    meanTruthHitRate = mean( ...
        truthHitRatePerFrame, ...
        "omitnan");

    targetTruthHitRate = mean( ...
        targetHitMatrix, ...
        1);

    %% Tracking metrics using current-frame truth

    targetTrackHitRate = mean( ...
        trackHitMatrix, ...
        1);

    meanTrackHitRate = mean( ...
        targetTrackHitRate, ...
        "omitnan");

    meanTrackPositionError = mean( ...
        trackPositionErrorPerFrame, ...
        1, ...
        "omitnan");

    %% Metrics excluding tracker initialization frame

    trackEvaluationFrames = 2:numSensingFrames;

    if isempty(trackEvaluationFrames)

        targetTrackHitRateNoInit = ...
            NaN(1, numTargets);

        meanTrackHitRateNoInit = NaN;

        meanTrackPositionErrorNoInit = ...
            NaN(1, numTargets);

        targetTrackHitRatePrevTruth = ...
            NaN(1, numTargets);

        meanTrackHitRatePrevTruth = NaN;

        meanTrackPositionErrorPrevTruth = ...
            NaN(1, numTargets);

    else

        targetTrackHitRateNoInit = mean( ...
            trackHitMatrix( ...
            trackEvaluationFrames, :), ...
            1);

        meanTrackHitRateNoInit = mean( ...
            targetTrackHitRateNoInit, ...
            "omitnan");

        meanTrackPositionErrorNoInit = mean( ...
            trackPositionErrorPerFrame( ...
            trackEvaluationFrames, :), ...
            1, ...
            "omitnan");

        %% Previous-frame truth diagnostic

        targetTrackHitRatePrevTruth = mean( ...
            trackHitPrevTruthMatrix( ...
            trackEvaluationFrames, :), ...
            1);

        meanTrackHitRatePrevTruth = mean( ...
            targetTrackHitRatePrevTruth, ...
            "omitnan");

        meanTrackPositionErrorPrevTruth = mean( ...
            trackPositionErrorPrevTruthPerFrame( ...
            trackEvaluationFrames, :), ...
            1, ...
            "omitnan");
    end
    %% Metrics summary in command window

    if config.printMetricsSummary

        fprintf('\n');
        fprintf('ISAC simulation metrics summary\n');
        fprintf('--------------------------------\n');

        fprintf('Scenario: %s\n', config.scenarioName);
        fprintf('Topology: %s\n', config.topology);
        fprintf('Target case: %s\n', config.targetCase);

        fprintf( ...
            'Mean clustered detections per frame: %.2f\n', ...
            meanNumDetections);

        fprintf( ...
            'Mean raw CFAR detections per frame: %.2f\n', ...
            meanNumRawCFARDetections);

        fprintf( ...
            'Mean active tracks per frame: %.2f\n', ...
            meanNumTracks);

        fprintf( ...
            'Total unique Track IDs: %d\n', ...
            totalTrackIDs);

        fprintf( ...
            'Total approximate extra tracks: %d\n', ...
            totalFalseTracks);

        fprintf( ...
            'Mean truth hit rate: %.2f %%\n', ...
            100 * meanTruthHitRate);

        for targetIndex = 1:numTargets

            fprintf( ...
                'Target %d truth hit rate: %.2f %%\n', ...
                targetIndex, ...
                100 * targetTruthHitRate(targetIndex));
        end

        fprintf( ...
            'Mean track hit rate: %.2f %%\n', ...
            100 * meanTrackHitRate);

        fprintf( ...
            'Mean track hit rate excluding first frame: %.2f %%\n', ...
            100 * meanTrackHitRateNoInit);

        fprintf( ...
            'Mean track hit rate versus previous-frame truth: %.2f %%\n', ...
            100 * meanTrackHitRatePrevTruth);

        for targetIndex = 1:numTargets

            fprintf( ...
                ['Target %d: track hit %.2f %% | ' ...
                'mean error %.2f m | ' ...
                'error excluding initialization %.2f m\n'], ...
                targetIndex, ...
                100 * targetTrackHitRate(targetIndex), ...
                meanTrackPositionError(targetIndex), ...
                meanTrackPositionErrorNoInit(targetIndex));
        end
    end
    %% Final visualisations

    trackingErrorFigure = [];
    speedHeadingFigure = [];

    if config.showTrackingErrorFigure

        trackingErrorFigure = ...
            helperPlotTrackPositionErrorPerFrame( ...
            trackPositionErrorPerFrame, ...
            config.trackDistanceTolerance, ...
            config.scenarioName, ...
            config.topology, ...
            config);
    end

    if config.showSpeedHeadingFigure

        speedHeadingFigure = ...
            helperPlotSpeedEstimationResults( ...
            simulationTime, ...
            targets.Trajectories, ...
            targetStateEstimates, ...
            trackIDs, ...
            config.scenarioName, ...
            config.topology, ...
            config);
    end
    %% Build results structure

    % During this first development stage, the function only returns the
    % prepared simulation configuration. The sensing loop is added next.

    results = struct();

    results.config = config;

    results.scenarioName = config.scenarioName;
    results.topology = config.topology;
    results.targetCase = config.targetCase;

    results.scenarioDescription = ...
        scenarioConfig.description;

    results.txPosition = txPosition;
    results.rxPosition = rxPosition;

    results.txOrientationAxes = txOrientationAxes;
    results.rxOrientationAxes = rxOrientationAxes;

    results.regionOfInterest = regionOfInterest;
    % Static scatterers used throughout the complete simulation.
    % Size: 3 x numScatterers, with rows [x; y; z].
    results.scattererPositions = scatterers.Positions;
    results.scattererReflectionCoefficients = ...
        scatterers.ReflectionCoefficients;
    results.scenarioPlotXLim = scenarioPlotXLim;
    results.scenarioPlotYLim = scenarioPlotYLim;

    results.numTargets = numTargets;
    results.numScatterers = numScatterers;

    results.carrierFrequency = carrierFrequency;
    results.transmissionBandwidth = transmissionBandwidth;

    results.rangeResolution = rangeResolution;
    results.maxRange = maxRange;
    results.maxVelocity = maxVelocity;
    results.maxDelay = maxDelay;
    results.baseline = baseline;

    results.dt = dt;
    results.numSensingFrames = numSensingFrames;
    %% Summary metrics

    results.totalTrackIDs = totalTrackIDs;

    results.meanNumDetections = ...
        meanNumDetections;

    results.meanNumRawCFARDetections = ...
        meanNumRawCFARDetections;

    results.meanNumTracks = ...
        meanNumTracks;

    results.totalFalseTracks = ...
        totalFalseTracks;

    results.meanFalseTracksPerFrame = ...
        meanFalseTracksPerFrame;

    results.meanTruthHitRate = ...
        meanTruthHitRate;

    results.targetTruthHitRate = ...
        targetTruthHitRate;

    results.targetTrackHitRate = ...
        targetTrackHitRate;

    results.meanTrackHitRate = ...
        meanTrackHitRate;

    results.meanTrackPositionError = ...
        meanTrackPositionError;

    results.targetTrackHitRateNoInit = ...
        targetTrackHitRateNoInit;

    results.meanTrackHitRateNoInit = ...
        meanTrackHitRateNoInit;

    results.meanTrackPositionErrorNoInit = ...
        meanTrackPositionErrorNoInit;

    results.targetTrackHitRatePrevTruth = ...
        targetTrackHitRatePrevTruth;

    results.meanTrackHitRatePrevTruth = ...
        meanTrackHitRatePrevTruth;

    results.meanTrackPositionErrorPrevTruth = ...
        meanTrackPositionErrorPrevTruth;

    results.trackDistanceTolerance = ...
        config.trackDistanceTolerance;

    results.truthRangeTolerance = ...
        config.truthRangeTolerance;

    results.truthAoATolerance = ...
        config.truthAoATolerance;

    results.trackingErrorFigure = ...
        trackingErrorFigure;

    results.speedHeadingFigure = ...
        speedHeadingFigure;
    results.simulationTime = simulationTime;
    %% Processing setup results

    results.aoaGrid = aoaGrid;
    results.aodGrid = aodGrid;
    results.rangeGrid = rangeGrid;

    results.numAoA = numAoA;
    results.numAoD = numAoD;
    results.numRange = numRange;

    results.aoaResolution = aoaResolution;
    results.rangeStep = rangeStep;

    results.numGuardCellsRange = ...
        numGuardCellsRange;

    results.numGuardCellsAoA = ...
        numGuardCellsAoA;

    results.numSubcarriers = ...
        numSubcarriers;

    results.numSymbolsPerFrame = ...
        numSymbolsPerFrame;

    results.processingSetupComplete = true;
    %% Frame-by-frame simulation results

    results.frames = playbackFrames;

    results.targetPositionsHistory = ...
        targetPositionsHistory;

    results.rangeAoAMapPerFrame = ...
        rangeAoAMapPerFrame;

    results.truthRangeAoAPerFrame = ...
        truthRangeAoAPerFrame;

    results.clusteredDetectionsPerFrame = ...
        clusteredDetectionsPerFrame;

    results.trackHistoryPerFrame = ...
        trackHistoryPerFrame;

    results.tracksRangeAoAPerFrame = ...
        tracksRangeAoAPerFrame;

    results.measuredPositionsPerFrame = ...
        measuredPositionsPerFrame;

    results.truthHitRatePerFrame = ...
        truthHitRatePerFrame;

    results.targetHitMatrix = ...
        targetHitMatrix;

    results.trackPositionErrorPerFrame = ...
        trackPositionErrorPerFrame;

    results.trackHitMatrix = ...
        trackHitMatrix;

    results.trackPositionErrorPrevTruthPerFrame = ...
        trackPositionErrorPrevTruthPerFrame;

    results.trackHitPrevTruthMatrix = ...
        trackHitPrevTruthMatrix;

    results.truthRangeSeparationPerFrame = ...
        truthRangeSeparationPerFrame;

    results.truthAoASeparationPerFrame = ...
        truthAoASeparationPerFrame;

    results.numDetectionsPerFrame = ...
        numDetectionsPerFrame;

    results.numRawCFARDetectionsPerFrame = ...
        numRawCFARDetectionsPerFrame;

    results.numTracksPerFrame = ...
        numTracksPerFrame;

    results.falseTracksPerFrame = ...
        falseTracksPerFrame;

    results.trackIDs = trackIDs;

    results.targetStateEstimates = ...
        targetStateEstimates;

    results.simulationComplete = true;
    results.setupComplete = true;
    %% Optional video export

    results.videoPath = "";

    if config.exportVideo

        if ~config.storePlaybackFrames
            error( ...
                ["Video export requires stored playback frames. " ...
                "Set config.storePlaybackFrames = true."]);
        end

        results.videoPath = exportISACVideo( ...
            results, ...
            config);
    end
end