function statusText = renderISACFrame( ...
    scenarioAxes, rangeAoAAxes, results, frameIndex)
%RENDERISACFRAME Render one stored ISAC simulation frame.
%
%   STATUSTEXT = RENDERISACFRAME(SCENARIOAXES, RANGEAOAAXES, RESULTS,
%   FRAMEINDEX) displays:
%
%       - Cartesian scenario, scatterers, Tx, Rx and trajectories
%       - Current targets, detections and tracks
%       - Track history up to the selected frame
%       - Range-AoA map
%       - Ground truth, clustered detections and track estimates
%
%   The function works with both standard axes and App Designer UIAxes.

    %% Validate frame index

    if ~isfield(results, "frames") || isempty(results.frames)
        error("The results structure does not contain playback frames.");
    end

    numFrames = numel(results.frames);

    validateattributes( ...
        frameIndex, ...
        {'numeric'}, ...
        {'scalar', 'integer', '>=', 1, '<=', numFrames});

    frame = results.frames(frameIndex);
    % Ensure that both axes remain visible in UI-based figures.
    scenarioAxes.Visible = 'on';
    rangeAoAAxes.Visible = 'on';

    %% Cartesian scenario

    cla(scenarioAxes);
    hold(scenarioAxes, 'on');

    % Static scatterers.
    if isfield(results, "scattererPositions") ...
            && ~isempty(results.scattererPositions)

        plot( ...
            scenarioAxes, ...
            results.scattererPositions(1, :), ...
            results.scattererPositions(2, :), ...
            '.', ...
            'MarkerSize', 6, ...
            'DisplayName', 'Scatterers');
    end

    % Complete true target trajectories.
    if isfield(results, "targetPositionsHistory") ...
            && ~isempty(results.targetPositionsHistory)

        numTargets = size(results.targetPositionsHistory, 2);

        for targetIndex = 1:numTargets

            trajectoryX = squeeze( ...
                results.targetPositionsHistory( ...
                    :, targetIndex, 1));

            trajectoryY = squeeze( ...
                results.targetPositionsHistory( ...
                    :, targetIndex, 2));

            plot( ...
                scenarioAxes, ...
                trajectoryX, ...
                trajectoryY, ...
                '--', ...
                'LineWidth', 1.2, ...
                'HandleVisibility', 'off');
        end
    end

    % Tx and Rx.
    plot( ...
        scenarioAxes, ...
        results.txPosition(1), ...
        results.txPosition(2), ...
        'o', ...
        'MarkerSize', 9, ...
        'LineWidth', 1.5, ...
        'DisplayName', 'Tx');

    plot( ...
        scenarioAxes, ...
        results.rxPosition(1), ...
        results.rxPosition(2), ...
        'v', ...
        'MarkerSize', 9, ...
        'LineWidth', 1.5, ...
        'DisplayName', 'Rx');

    % Current true target positions.
    targetPositions = frame.targetPositions;

    if ~isempty(targetPositions)

        plot( ...
            scenarioAxes, ...
            targetPositions(:, 1), ...
            targetPositions(:, 2), ...
            'x', ...
            'MarkerSize', 10, ...
            'LineWidth', 2, ...
            'DisplayName', 'Targets');

        for targetIndex = 1:size(targetPositions, 1)

            text( ...
                scenarioAxes, ...
                targetPositions(targetIndex, 1) + 1, ...
                targetPositions(targetIndex, 2) + 1, ...
                sprintf('Target %d', targetIndex));
        end
    end

    % Current Cartesian detections.
    measuredPositions = frame.measuredPositions;

    if ~isempty(measuredPositions)

        if size(measuredPositions, 1) == 3

            measuredX = measuredPositions(1, :);
            measuredY = measuredPositions(2, :);

        else

            measuredX = measuredPositions(:, 1);
            measuredY = measuredPositions(:, 2);
        end

        plot( ...
            scenarioAxes, ...
            measuredX, ...
            measuredY, ...
            'o', ...
            'MarkerSize', 6, ...
            'LineWidth', 1.2, ...
            'DisplayName', 'Detections');
    end

    %% Track history

    trackIDsSeen = [];

    for previousFrameIndex = 1:frameIndex

        previousTracks = ...
            results.frames(previousFrameIndex).tracks;

        for trackIndex = 1:numel(previousTracks)

            trackID = previousTracks(trackIndex).TrackID;

            trackIDsSeen = union( ...
                trackIDsSeen, ...
                trackID);
        end
    end

    for trackID = trackIDsSeen

        trackX = [];
        trackY = [];

        for previousFrameIndex = 1:frameIndex

            previousTracks = ...
                results.frames(previousFrameIndex).tracks;

            for trackIndex = 1:numel(previousTracks)

                if previousTracks(trackIndex).TrackID == trackID

                    state = previousTracks(trackIndex).State;

                    trackX(end + 1) = state(1); %#ok<AGROW>
                    trackY(end + 1) = state(3); %#ok<AGROW>
                end
            end
        end

        plot( ...
            scenarioAxes, ...
            trackX, ...
            trackY, ...
            '-', ...
            'LineWidth', 1.4, ...
            'HandleVisibility', 'off');
    end

    %% Current tracks

    currentTracks = frame.tracks;

    if ~isempty(currentTracks)

        trackX = zeros(1, numel(currentTracks));
        trackY = zeros(1, numel(currentTracks));

        for trackIndex = 1:numel(currentTracks)

            state = currentTracks(trackIndex).State;

            trackX(trackIndex) = state(1);
            trackY(trackIndex) = state(3);
        end

        plot( ...
            scenarioAxes, ...
            trackX, ...
            trackY, ...
            's', ...
            'MarkerSize', 7, ...
            'LineWidth', 1.5, ...
            'DisplayName', 'Tracks');

        for trackIndex = 1:numel(currentTracks)

            text( ...
                scenarioAxes, ...
                trackX(trackIndex) + 1, ...
                trackY(trackIndex) - 1, ...
                sprintf( ...
                    'Track %d', ...
                    currentTracks(trackIndex).TrackID));
        end
    end

    %% Scenario axes formatting

    xlim( ...
        scenarioAxes, ...
        results.scenarioPlotXLim(:).');

    ylim( ...
        scenarioAxes, ...
        results.scenarioPlotYLim(:).');

    axis(scenarioAxes, 'equal');

    grid(scenarioAxes, 'on');
    box(scenarioAxes, 'on');

    xlabel(scenarioAxes, 'x [m]');
    ylabel(scenarioAxes, 'y [m]');

    title( ...
        scenarioAxes, ...
        sprintf( ...
            'Cartesian scenario - frame %d', ...
            frameIndex), ...
        'Interpreter', 'none');

    legend( ...
    scenarioAxes, ...
    'Location', 'northeast');
    hold(scenarioAxes, 'off');

    %% Range-AoA map

    cla(rangeAoAAxes);

    imagesc( ...
        rangeAoAAxes, ...
        results.aoaGrid, ...
        results.rangeGrid, ...
        frame.rangeAoAMap);

    rangeAoAAxes.YDir = 'normal';

    colormap(rangeAoAAxes, 'gray');

    hold(rangeAoAAxes, 'on');

    % Ground truth.
    truthRangeAoA = frame.truthRangeAoA;

    if ~isempty(truthRangeAoA)

        plot( ...
            rangeAoAAxes, ...
            truthRangeAoA(2, :), ...
            truthRangeAoA(1, :), ...
            'x', ...
            'MarkerSize', 10, ...
            'LineWidth', 2, ...
            'DisplayName', 'Truth');
    end

    % Clustered CFAR detections.
    clusteredDetections = frame.clusteredDetections;

    if ~isempty(clusteredDetections)

        plot( ...
            rangeAoAAxes, ...
            clusteredDetections(2, :), ...
            clusteredDetections(1, :), ...
            'o', ...
            'MarkerSize', 7, ...
            'LineWidth', 1.5, ...
            'DisplayName', 'Clustered detections');
    end

    % Current track estimates in range-AoA.
    trackRangeAoA = frame.trackRangeAoA;

    if ~isempty(trackRangeAoA)

        plot( ...
            rangeAoAAxes, ...
            trackRangeAoA(2, :), ...
            trackRangeAoA(1, :), ...
            's', ...
            'MarkerSize', 7, ...
            'LineWidth', 1.5, ...
            'DisplayName', 'Tracks');
    end

    xlabel(rangeAoAAxes, 'AoA [deg]');

    if results.topology == "bistatic"

        ylabel(rangeAoAAxes, 'Bistatic range [m]');

    else

        ylabel(rangeAoAAxes, 'Monostatic range [m]');
    end

    title( ...
        rangeAoAAxes, ...
        'Range-AoA map');

   legend( ...
    rangeAoAAxes, ...
    'Location', 'northeast');

    hold(rangeAoAAxes, 'off');

    %% Status

    statusText = sprintf( ...
        'Frame %d of %d | Simulation time: %.1f s | %s / %s', ...
        frameIndex, ...
        numFrames, ...
        frame.simulationTime, ...
        results.scenarioName, ...
        results.topology);

    
end